server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.94.218.214:3306/demo?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://39.105.121.1:9002/test01?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root


  rabbitmq:
    host: 47.94.218.214
    port: 5672
    username: admin
    password: w130830w
    virtual-host: /


logging:
  level:
    com.example.demo.mapper.UserMapper: debug
