server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.218.214:3306/demo?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1+1=2...


logging:
  level:
    com.example.demo.mapper.UserMapper: debug
